### ISSUE TITLE
Missing person id

### ISSUE THREAD

**Issue by maknol** [dhobi/PHP-IMDb-Scraper#9]
Hi, now working fine, but person id is missing, only name is feched.

**Comment by dhobi** [comment]
Ok, I thought that noone is using this and removed it. My fault, sorry, will restore it as soon as possible.

**Comment by dhobi** [comment]
I pushed some changes to have the person id as well. Could you verify and close the issue afterwards?

**Comment by pemtorrent** [comment]
hello, nope still get name characters who actors play in movie
and Country with Language is missing
thanks for your hard work.

**Comment by maknol** [comment]
Hi, yes, working! Thank you!

**Comment by dhobi** [comment]
No problem, closed.
